// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'evaluation_test.dart' as evaluation_test;
import 'flags_test.dart' as flags_test;

void main() {
  evaluation_test.main();
  flags_test.main();
}
