name: flagr
version: 1.1.8+2
description: Flagr API client. Flagr is a feature flagging, A/B testing and dynamic configuration microservice.
homepage: https://github.com/amondnet/flagr.dart
repository: https://github.com/amondnet/flagr.dart

environment:
    sdk: ">=2.3.0 <3.0.0"

dependencies:
    dio: ^3.0.9
    built_value: ^7.1.0
    built_collection: ^4.3.2
    time_machine: ^0.9.12
    meta: ^1.1.8

dev_dependencies:
    built_value_generator: ^7.1.0
    build_runner: ^1.7.1
    test: ^1.14.6
    build_test: ^1.0.0
    mock_web_server: ^4.1.1
    pedantic: ^1.9.0
    test_coverage: ^0.4.1


